#!/bin/bash

# A bash script to run the main function of the bot.

# Check the input argument to determine mode first
case "$1" in
    prod|dev)
        # Valid input; proceed with setup
        ;;
    *)
        echo "Invalid mode. Usage: $0 [dev|prod]"
        exit 1
        ;;
esac

# Check if Poetry is installed
if ! command -v poetry &> /dev/null
then
    echo "Poetry could not be found. Please install it from https://python-poetry.org/docs/#installing-with-the-official-installer"
    exit 1
fi

# install the project dependencies using Poetry
poetry install

# Execute based on the input mode
if [ "$1" == "prod" ]; then
    echo "Running in production mode..."
    # Running Python in optimized mode
    poetry run python -O -c "from src.main import main; main()"
else
    echo "Running in development mode..."
    # Running Python normally
    poetry run python -c "from src.main import main; main()"
fi