"""
Contains all direct interactions with the Politics and War API.

The submodule `/api_v3` has been automatically generated by `ariadne-codegen` 
from `pnw_api_schema.graphql` in the resources directory. Do not modify this directly.
"""
