# Generated by ariadne-codegen
# Source: resources/queries.graphql

from datetime import date
from typing import List, Optional

from pydantic import AwareDatetime, Field

from .base_model import BaseModel
from .enums import (
    DomesticPolicy,
    EconomicPolicy,
    GovernmentType,
    SocialPolicy,
    WarPolicy,
)


class AlliancePositionFields(BaseModel):
    id: str
    date: AwareDatetime
    alliance_id: str
    name: str
    creator_id: str
    last_editor_id: str
    date_modified: AwareDatetime
    position_level: int
    leader: bool
    heir: bool
    officer: bool
    member: bool
    permissions: int


class AllianceFields(BaseModel):
    id: str
    name: str
    acronym: str
    score: float
    color: str
    date: AwareDatetime
    average_score: Optional[float]
    accept_members: bool
    flag: str
    rank: int
    alliance_positions: List["AllianceFieldsAlliancePositions"]


class AllianceFieldsAlliancePositions(AlliancePositionFields):
    pass


class CityFields(BaseModel):
    id: str
    nation_id: str
    name: str
    nuke_date: Optional[str]
    date: date
    infrastructure: float
    land: float
    powered: bool
    oil_power: int
    wind_power: int
    coal_power: int
    nuclear_power: int
    coal_mine: int
    oil_well: int
    uranium_mine: int
    barracks: int
    farm: int
    police_station: int
    hospital: int
    recycling_center: int
    subway: int
    supermarket: int
    bank: int
    shopping_mall: int
    stadium: int
    lead_mine: int
    iron_mine: int
    bauxite_mine: int
    oil_refinery: int
    aluminum_refinery: int
    steel_mill: int
    munitions_factory: int
    factory: int
    hangar: int
    drydock: int


class NationFields(BaseModel):
    id: str
    alliance_id: Optional[str]
    alliance_obj: Optional["NationFieldsAllianceObj"]
    alliance_position_id: Optional[str]
    nation_name: str
    leader_name: str
    continent: str
    war_policy: WarPolicy
    war_policy_turns: int
    domestic_policy: DomesticPolicy
    domestic_policy_turns: int
    color: str
    num_cities: int
    score: float
    update_tz: Optional[float]
    population: int
    flag: str
    vacation_mode_turns: int
    beige_turns: int
    espionage_available: bool
    last_active: AwareDatetime
    date: AwareDatetime
    soldiers: int
    tanks: int
    aircraft: int
    ships: int
    missiles: int
    nukes: int
    spies: int
    discord: str
    discord_id: Optional[str]
    turns_since_last_city: int
    turns_since_last_project: int
    projects: int
    project_bits: str
    moon_landing_date: Optional[AwareDatetime]
    mars_landing_date: Optional[AwareDatetime]
    wars_won: int
    wars_lost: int
    tax_id: str
    alliance_seniority: int
    gross_national_income: float
    gross_domestic_product: float
    soldier_casualties: int
    soldier_kills: int
    tank_casualties: int
    tank_kills: int
    aircraft_casualties: int
    aircraft_kills: int
    ship_casualties: int
    ship_kills: int
    missile_casualties: int
    missile_kills: int
    nuke_casualties: int
    nuke_kills: int
    spy_casualties: Optional[int]
    spy_kills: Optional[int]
    spy_attacks: Optional[int]
    money_looted: float
    total_infrastructure_destroyed: float
    total_infrastructure_lost: float
    vip: bool
    commendations: int
    denouncements: int
    offensive_wars_count: int
    defensive_wars_count: int
    economic_policy: EconomicPolicy
    social_policy: SocialPolicy
    government_type: GovernmentType
    credits_redeemed_this_month: Optional[int]
    alliance_join_date: Optional[AwareDatetime]


class NationFieldsAllianceObj(BaseModel):
    id: str


class PaginatorFields(BaseModel):
    count: int
    has_more_pages: bool = Field(alias="hasMorePages")


AlliancePositionFields.model_rebuild()
AllianceFields.model_rebuild()
CityFields.model_rebuild()
NationFields.model_rebuild()
PaginatorFields.model_rebuild()
