# Generated by ariadne-codegen
# Source: resources/queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import NationFields, PaginatorFields


class GetNations(BaseModel):
    nations: "GetNationsNations"


class GetNationsNations(BaseModel):
    data: List["GetNationsNationsData"]
    paginator_info: "GetNationsNationsPaginatorInfo" = Field(alias="paginatorInfo")


class GetNationsNationsData(NationFields):
    pass


class GetNationsNationsPaginatorInfo(PaginatorFields):
    pass


GetNations.model_rebuild()
GetNationsNations.model_rebuild()
