# Generated by ariadne-codegen
# Source: resources/pnw_api_schema.graphql

from .base_model import BaseModel
from .enums import (
    AllianceBankrecsOrderByColumn,
    AllianceBulletinsOrderByColumn,
    AllianceNationsOrderByColumn,
    AllianceTaxBracketsOrderByColumn,
    AllianceTaxrecsOrderByColumn,
    AllianceTreatiesOrderByColumn,
    AllianceWarsOrderByColumn,
    BBTeamGamesOrderByColumn,
    NationBankrecsOrderByColumn,
    NationBulletinRepliesOrderByColumn,
    NationBulletinsOrderByColumn,
    NationTaxrecsOrderByColumn,
    NationTradesOrderByColumn,
    NationWarsOrderByColumn,
    QueryActivityStatsOrderByColumn,
    QueryAlliancesOrderByColumn,
    QueryBankrecsOrderByColumn,
    QueryBannedNationsOrderByColumn,
    QueryBaseballGamesOrderByColumn,
    QueryBaseballPlayersOrderByColumn,
    QueryBaseballTeamsOrderByColumn,
    QueryBountiesOrderByColumn,
    QueryBulletinRepliesOrderByColumn,
    QueryBulletinsOrderByColumn,
    QueryCitiesOrderByColumn,
    QueryEmbargoesOrderByColumn,
    QueryNationResourceStatsOrderByColumn,
    QueryNationsOrderByColumn,
    QueryResourceStatsOrderByColumn,
    QueryTradesOrderByColumn,
    QueryTreasureTradesOrderByColumn,
    QueryTreatiesOrderByColumn,
    QueryWarattacksOrderByColumn,
    QueryWarsOrderByColumn,
    SortOrder,
    WarAttacksOrderByColumn,
)


class AllianceNationsOrderByOrderByClause(BaseModel):
    column: AllianceNationsOrderByColumn
    order: SortOrder


class AllianceTreatiesOrderByOrderByClause(BaseModel):
    column: AllianceTreatiesOrderByColumn
    order: SortOrder


class AllianceBankrecsOrderByOrderByClause(BaseModel):
    column: AllianceBankrecsOrderByColumn
    order: SortOrder


class AllianceTaxrecsOrderByOrderByClause(BaseModel):
    column: AllianceTaxrecsOrderByColumn
    order: SortOrder


class AllianceTaxBracketsOrderByOrderByClause(BaseModel):
    column: AllianceTaxBracketsOrderByColumn
    order: SortOrder


class AllianceWarsOrderByOrderByClause(BaseModel):
    column: AllianceWarsOrderByColumn
    order: SortOrder


class WarAttacksOrderByOrderByClause(BaseModel):
    column: WarAttacksOrderByColumn
    order: SortOrder


class AllianceBulletinsOrderByOrderByClause(BaseModel):
    column: AllianceBulletinsOrderByColumn
    order: SortOrder


class NationWarsOrderByOrderByClause(BaseModel):
    column: NationWarsOrderByColumn
    order: SortOrder


class NationBankrecsOrderByOrderByClause(BaseModel):
    column: NationBankrecsOrderByColumn
    order: SortOrder


class NationTradesOrderByOrderByClause(BaseModel):
    column: NationTradesOrderByColumn
    order: SortOrder


class NationTaxrecsOrderByOrderByClause(BaseModel):
    column: NationTaxrecsOrderByColumn
    order: SortOrder


class BBTeamGamesOrderByOrderByClause(BaseModel):
    column: BBTeamGamesOrderByColumn
    order: SortOrder


class NationBulletinsOrderByOrderByClause(BaseModel):
    column: NationBulletinsOrderByColumn
    order: SortOrder


class NationBulletinRepliesOrderByOrderByClause(BaseModel):
    column: NationBulletinRepliesOrderByColumn
    order: SortOrder


class QueryNationResourceStatsOrderByOrderByClause(BaseModel):
    column: QueryNationResourceStatsOrderByColumn
    order: SortOrder


class QueryNationsOrderByOrderByClause(BaseModel):
    column: QueryNationsOrderByColumn
    order: SortOrder


class QueryAlliancesOrderByOrderByClause(BaseModel):
    column: QueryAlliancesOrderByColumn
    order: SortOrder


class QueryTradesOrderByOrderByClause(BaseModel):
    column: QueryTradesOrderByColumn
    order: SortOrder


class QueryWarsOrderByOrderByClause(BaseModel):
    column: QueryWarsOrderByColumn
    order: SortOrder


class QueryBountiesOrderByOrderByClause(BaseModel):
    column: QueryBountiesOrderByColumn
    order: SortOrder


class QueryWarattacksOrderByOrderByClause(BaseModel):
    column: QueryWarattacksOrderByColumn
    order: SortOrder


class QueryTreatiesOrderByOrderByClause(BaseModel):
    column: QueryTreatiesOrderByColumn
    order: SortOrder


class QueryCitiesOrderByOrderByClause(BaseModel):
    column: QueryCitiesOrderByColumn
    order: SortOrder


class QueryBankrecsOrderByOrderByClause(BaseModel):
    column: QueryBankrecsOrderByColumn
    order: SortOrder


class QueryBaseballGamesOrderByOrderByClause(BaseModel):
    column: QueryBaseballGamesOrderByColumn
    order: SortOrder


class QueryBaseballTeamsOrderByOrderByClause(BaseModel):
    column: QueryBaseballTeamsOrderByColumn
    order: SortOrder


class QueryBaseballPlayersOrderByOrderByClause(BaseModel):
    column: QueryBaseballPlayersOrderByColumn
    order: SortOrder


class QueryTreasureTradesOrderByOrderByClause(BaseModel):
    column: QueryTreasureTradesOrderByColumn
    order: SortOrder


class QueryEmbargoesOrderByOrderByClause(BaseModel):
    column: QueryEmbargoesOrderByColumn
    order: SortOrder


class QueryResourceStatsOrderByOrderByClause(BaseModel):
    column: QueryResourceStatsOrderByColumn
    order: SortOrder


class QueryActivityStatsOrderByOrderByClause(BaseModel):
    column: QueryActivityStatsOrderByColumn
    order: SortOrder


class QueryBannedNationsOrderByOrderByClause(BaseModel):
    column: QueryBannedNationsOrderByColumn
    order: SortOrder


class QueryBulletinsOrderByOrderByClause(BaseModel):
    column: QueryBulletinsOrderByColumn
    order: SortOrder


class QueryBulletinRepliesOrderByOrderByClause(BaseModel):
    column: QueryBulletinRepliesOrderByColumn
    order: SortOrder


class OrderByClause(BaseModel):
    column: str
    order: SortOrder
