# Generated by ariadne-codegen
# Source: resources/queries.graphql

from pydantic import Field

from .base_model import BaseModel


class MutationBankWithdraw(BaseModel):
    bank_withdraw: "MutationBankWithdrawBankWithdraw" = Field(alias="bankWithdraw")


class MutationBankWithdrawBankWithdraw(BaseModel):
    id: str


MutationBankWithdraw.model_rebuild()
