#!/bin/bash

# A bash script to set up the environment and run the main function of the program.
# 
# This script serves several purposes:
# 1. It handles mode selection (production or development) and runs the program accordingly.
# 2. It checks for Poetry, ensuring that the project's dependencies are managed in an isolated environment.
# 3. It installs project dependencies using Poetry.
# 4. It runs the main function from the src.main module instead of the script directly.
#    - This approach ensures that relative imports within the src package work correctly.
#    - Running the script directly (e.g., python src/main.py) can break relative imports because
#      Python does not recognize the script as part of a package.

# Check the input argument to determine the mode (prod or dev).
case "$1" in
    prod|dev)
        # Valid input; proceed with setup.
        ;;
    *)
        # Invalid input; display usage information and exit.
        echo "Invalid mode. Usage: $0 [dev|prod]"
        exit 1
        ;;
esac

# Check if Poetry is installed
if ! command -v poetry &> /dev/null; then
    # Poetry is not installed; prompt user to install it and exit.
    echo "Poetry could not be found. Please install it from https://python-poetry.org/docs/#installing-with-the-official-installer"
    exit 1
fi

# Install the project dependencies using Poetry.
poetry install --sync

# Check for pending migrations using `piccolo migrations check komodo`
MIGRATIONS_OUTPUT=$(piccolo migrations check komodo)

if echo "$MIGRATIONS_OUTPUT" | grep -q "| False"; then
    # If there are pending migrations, migrate the database
    echo "There are pending migrations. Migrating the database..."
    piccolo migrations forward komodo
fi


# Execute based on the input mode
if [ "$1" == "prod" ]; then
    echo "Running in production mode..."
    # Running Python in optimized mode (-O).
    poetry run python -O -c "from src.main import main; main()"
else
    echo "Running in development mode..."
    # Running Python normally without optimizations.
    poetry run python -c "from src.main import main; main()"
fi