# Generated by ariadne-codegen
# Source: resources/pnw_api_schema.graphql

from enum import Enum


class AlliancePositionEnum(str, Enum):
    NOALLIANCE = "NOALLIANCE"
    APPLICANT = "APPLICANT"
    MEMBER = "MEMBER"
    OFFICER = "OFFICER"
    HEIR = "HEIR"
    LEADER = "LEADER"


class AllianceNationsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    SOLDIERS = "SOLDIERS"
    TANKS = "TANKS"
    AIRCRAFT = "AIRCRAFT"
    SHIPS = "SHIPS"
    MISSILES = "MISSILES"
    NUKES = "NUKES"
    CITIES = "CITIES"


class SortOrder(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class AllianceTreatiesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    TURNS_LEFT = "TURNS_LEFT"


class AllianceBankrecsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    MONEY = "MONEY"
    COAL = "COAL"
    OIL = "OIL"
    URANIUM = "URANIUM"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    LEAD = "LEAD"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    FOOD = "FOOD"


class AllianceTaxrecsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    MONEY = "MONEY"
    COAL = "COAL"
    OIL = "OIL"
    URANIUM = "URANIUM"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    LEAD = "LEAD"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    FOOD = "FOOD"


class AllianceTaxBracketsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    DATE_MODIFIED = "DATE_MODIFIED"
    TAX_RATE = "TAX_RATE"
    RESOURCE_RAX_RATE = "RESOURCE_RAX_RATE"


class WarActivity(str, Enum):
    ALL = "ALL"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class AllianceWarsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"


class WarType(str, Enum):
    ORDINARY = "ORDINARY"
    ATTRITION = "ATTRITION"
    RAID = "RAID"


class WarAttacksOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"


class AttackType(str, Enum):
    AIRVINFRA = "AIRVINFRA"
    AIRVSOLDIERS = "AIRVSOLDIERS"
    AIRVTANKS = "AIRVTANKS"
    AIRVMONEY = "AIRVMONEY"
    AIRVSHIPS = "AIRVSHIPS"
    AIRVAIR = "AIRVAIR"
    GROUND = "GROUND"
    MISSILE = "MISSILE"
    MISSILEFAIL = "MISSILEFAIL"
    NUKE = "NUKE"
    NUKEFAIL = "NUKEFAIL"
    NAVAL = "NAVAL"
    FORTIFY = "FORTIFY"
    PEACE = "PEACE"
    VICTORY = "VICTORY"
    ALLIANCELOOT = "ALLIANCELOOT"


class AllianceBulletinsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    LAST_EDIT_DATE = "LAST_EDIT_DATE"
    ACCOUNT_ID = "ACCOUNT_ID"


class WarPolicy(str, Enum):
    ATTRITION = "ATTRITION"
    TURTLE = "TURTLE"
    BLITZKRIEG = "BLITZKRIEG"
    FORTRESS = "FORTRESS"
    MONEYBAGS = "MONEYBAGS"
    PIRATE = "PIRATE"
    TACTICIAN = "TACTICIAN"
    GUARDIAN = "GUARDIAN"
    COVERT = "COVERT"
    ARCANE = "ARCANE"


class DomesticPolicy(str, Enum):
    MANIFEST_DESTINY = "MANIFEST_DESTINY"
    OPEN_MARKETS = "OPEN_MARKETS"
    TECHNOLOGICAL_ADVANCEMENT = "TECHNOLOGICAL_ADVANCEMENT"
    IMPERIALISM = "IMPERIALISM"
    URBANIZATION = "URBANIZATION"
    RAPID_EXPANSION = "RAPID_EXPANSION"


class NationWarsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"


class NationBankrecsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    MONEY = "MONEY"
    COAL = "COAL"
    OIL = "OIL"
    URANIUM = "URANIUM"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    LEAD = "LEAD"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    FOOD = "FOOD"


class TradeType(str, Enum):
    GLOBAL = "GLOBAL"
    PERSONAL = "PERSONAL"
    ALLIANCE = "ALLIANCE"


class NationTradesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    DATE_ACCEPTED = "DATE_ACCEPTED"
    OFFER_RESOURCE = "OFFER_RESOURCE"
    OFFER_AMOUNT = "OFFER_AMOUNT"
    RETURN_AMOUNT = "RETURN_AMOUNT"


class NationTaxrecsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    MONEY = "MONEY"
    COAL = "COAL"
    OIL = "OIL"
    URANIUM = "URANIUM"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    LEAD = "LEAD"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    FOOD = "FOOD"


class BountyType(str, Enum):
    ORDINARY = "ORDINARY"
    ATTRITION = "ATTRITION"
    RAID = "RAID"
    NUCLEAR = "NUCLEAR"


class BBTeamGamesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    HTSCORE = "HTSCORE"
    ATSCORE = "ATSCORE"


class EconomicPolicy(str, Enum):
    EXTREME_LEFT = "EXTREME_LEFT"
    FAR_LEFT = "FAR_LEFT"
    LEFT = "LEFT"
    MODERATE = "MODERATE"
    RIGHT = "RIGHT"
    FAR_RIGHT = "FAR_RIGHT"
    EXTREME_RIGHT = "EXTREME_RIGHT"


class SocialPolicy(str, Enum):
    ANARCHIST = "ANARCHIST"
    LIBERTARIAN = "LIBERTARIAN"
    LIBERAL = "LIBERAL"
    MODERATE = "MODERATE"
    CONSERVATIVE = "CONSERVATIVE"
    AUTHORITARIAN = "AUTHORITARIAN"
    FASCIST = "FASCIST"


class GovernmentType(str, Enum):
    ABSOLUTE_MONARCHY = "ABSOLUTE_MONARCHY"
    ANARCHY = "ANARCHY"
    ARISTOCRACY = "ARISTOCRACY"
    BANANA_REPUBLIC = "BANANA_REPUBLIC"
    COMMUNIST_DEMOCRACY = "COMMUNIST_DEMOCRACY"
    COMMUNIST_DICTATORSHIP = "COMMUNIST_DICTATORSHIP"
    COMMUNIST_MONARCHY = "COMMUNIST_MONARCHY"
    COMMUNIST_REPUBLIC = "COMMUNIST_REPUBLIC"
    COMMUNIST_THEOCRACY = "COMMUNIST_THEOCRACY"
    CONSTITUTIONAL_MONARCHY = "CONSTITUTIONAL_MONARCHY"
    CONSTITUTIONAL_REPUBLIC = "CONSTITUTIONAL_REPUBLIC"
    DEMARCHY = "DEMARCHY"
    DEMOCRACY = "DEMOCRACY"
    DEMOCRATIC_REPUBLIC = "DEMOCRATIC_REPUBLIC"
    DICTATORSHIP = "DICTATORSHIP"
    FEDERAL_REPUBLIC = "FEDERAL_REPUBLIC"
    MONARCHY = "MONARCHY"
    NOOCRACY = "NOOCRACY"
    OLIGARCHY = "OLIGARCHY"
    PARLIAMENTARY_DEMOCRACY = "PARLIAMENTARY_DEMOCRACY"
    PARLIAMENTARY_REPUBLIC = "PARLIAMENTARY_REPUBLIC"
    PEOPLES_REPUBLIC = "PEOPLES_REPUBLIC"
    REPUBLIC = "REPUBLIC"
    SOCIAL_DEMOCRACY = "SOCIAL_DEMOCRACY"
    SOCIALIST_DICTATORSHIP = "SOCIALIST_DICTATORSHIP"
    SOCIALIST_REPUBLIC = "SOCIALIST_REPUBLIC"
    SOCIALIST_THEOCRACY = "SOCIALIST_THEOCRACY"
    STRATOCRACY = "STRATOCRACY"
    TECHNOCRACY = "TECHNOCRACY"
    THEOCRACY = "THEOCRACY"
    THEOCRATIC_DEMOCRACY = "THEOCRATIC_DEMOCRACY"
    THEOCRATIC_DICTATORSHIP = "THEOCRATIC_DICTATORSHIP"
    THEOCRATIC_REPUBLIC = "THEOCRATIC_REPUBLIC"
    MINDHIVE = "MINDHIVE"


class NationBulletinsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    LAST_EDIT_DATE = "LAST_EDIT_DATE"


class NationBulletinRepliesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    EDIT_DATE = "EDIT_DATE"
    BULLETIN_ID = "BULLETIN_ID"


class Resources(str, Enum):
    FOOD = "FOOD"
    COAL = "COAL"
    OIL = "OIL"
    URANIUM = "URANIUM"
    LEAD = "LEAD"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    CREDIT = "CREDIT"


class QueryNationResourceStatsOrderByColumn(str, Enum):
    DATE = "DATE"
    MONEY = "MONEY"
    FOOD = "FOOD"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    URANIUM = "URANIUM"
    COAL = "COAL"
    OIL = "OIL"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    LEAD = "LEAD"


class Continents(str, Enum):
    AFRICA = "AFRICA"
    ANTARCTICA = "ANTARCTICA"
    ASIA = "ASIA"
    AUSTRALIA = "AUSTRALIA"
    EUROPE = "EUROPE"
    NORTH_AMERICA = "NORTH_AMERICA"
    SOUTH_AMERICA = "SOUTH_AMERICA"


class QueryNationsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    SOLDIERS = "SOLDIERS"
    SOLDIERS_LOST = "SOLDIERS_LOST"
    SOLDIER_KILLS = "SOLDIER_KILLS"
    TANKS = "TANKS"
    TANKS_LOST = "TANKS_LOST"
    TANK_KILLS = "TANK_KILLS"
    AIRCRAFT = "AIRCRAFT"
    AIRCRAFT_LOST = "AIRCRAFT_LOST"
    AIRCRAFT_KILLS = "AIRCRAFT_KILLS"
    SHIPS = "SHIPS"
    SHIPS_LOST = "SHIPS_LOST"
    SHIP_KILLS = "SHIP_KILLS"
    MISSILES = "MISSILES"
    MISSILES_LAUNCHED = "MISSILES_LAUNCHED"
    MISSILES_EATEN = "MISSILES_EATEN"
    NUKES = "NUKES"
    NUKES_LAUNCHED = "NUKES_LAUNCHED"
    NUKES_EATEN = "NUKES_EATEN"
    CITIES = "CITIES"
    SCORE = "SCORE"
    GDP = "GDP"
    POPULATION = "POPULATION"
    APPROVAL_RATING = "APPROVAL_RATING"
    INFRA_DESTROYED = "INFRA_DESTROYED"
    INFRA_LOST = "INFRA_LOST"


class QueryAlliancesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    SCORE = "SCORE"


class QueryTradesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    DATE_ACCEPTED = "DATE_ACCEPTED"
    OFFER_RESOURCE = "OFFER_RESOURCE"
    OFFER_AMOUNT = "OFFER_AMOUNT"
    RETURN_AMOUNT = "RETURN_AMOUNT"
    PRICE = "PRICE"


class QueryWarsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"


class QueryBountiesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    AMOUNT = "AMOUNT"


class QueryWarattacksOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"


class QueryTreatiesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    TURNS_LEFT = "TURNS_LEFT"


class QueryCitiesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    MAXINFRA = "MAXINFRA"
    LAND = "LAND"


class QueryBankrecsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    MONEY = "MONEY"
    COAL = "COAL"
    OIL = "OIL"
    URANIUM = "URANIUM"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    LEAD = "LEAD"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    FOOD = "FOOD"


class QueryBaseballGamesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    HTSCORE = "HTSCORE"
    ATSCORE = "ATSCORE"


class QueryBaseballTeamsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    QUALITY = "QUALITY"
    SEATING = "SEATING"
    RATING = "RATING"
    WINS = "WINS"
    GLOSSES = "GLOSSES"
    RUNS = "RUNS"
    HOMERS = "HOMERS"
    STRIKEOUTS = "STRIKEOUTS"
    GAMES = "GAMES"


class QueryBaseballPlayersOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    AGE = "AGE"
    PITCHING = "PITCHING"
    BATTING = "BATTING"
    SPEED = "SPEED"
    AWARENESS = "AWARENESS"
    OVERALL = "OVERALL"


class QueryTreasureTradesOrderByColumn(str, Enum):
    ID = "ID"


class QueryEmbargoesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"


class EmbargoType(str, Enum):
    NATION_TO_NATION = "NATION_TO_NATION"
    NATION_TO_ALLIANCE = "NATION_TO_ALLIANCE"
    ALLIANCE_TO_NATION = "ALLIANCE_TO_NATION"
    ALLIANCE_TO_ALLIANCE = "ALLIANCE_TO_ALLIANCE"


class QueryResourceStatsOrderByColumn(str, Enum):
    DATE = "DATE"
    MONEY = "MONEY"
    FOOD = "FOOD"
    STEEL = "STEEL"
    ALUMINUM = "ALUMINUM"
    GASOLINE = "GASOLINE"
    MUNITIONS = "MUNITIONS"
    URANIUM = "URANIUM"
    COAL = "COAL"
    OIL = "OIL"
    IRON = "IRON"
    BAUXITE = "BAUXITE"
    LEAD = "LEAD"


class QueryActivityStatsOrderByColumn(str, Enum):
    DATE = "DATE"
    TOTAL_NATIONS = "TOTAL_NATIONS"
    NATIONS_CREATED = "NATIONS_CREATED"
    ACTIVE_1_DAY = "ACTIVE_1_DAY"
    ACTIVE_2_DAYS = "ACTIVE_2_DAYS"
    ACTIVE_3_DAYS = "ACTIVE_3_DAYS"
    ACTIVE_1_WEEK = "ACTIVE_1_WEEK"
    ACTIVE_1_MONTH = "ACTIVE_1_MONTH"


class QueryBannedNationsOrderByColumn(str, Enum):
    NATION_ID = "NATION_ID"
    DATE = "DATE"


class QueryBulletinsOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    LAST_EDIT_DATE = "LAST_EDIT_DATE"
    ACCOUNT_ID = "ACCOUNT_ID"


class QueryBulletinRepliesOrderByColumn(str, Enum):
    ID = "ID"
    DATE = "DATE"
    EDIT_DATE = "EDIT_DATE"
    ACCOUNT_ID = "ACCOUNT_ID"
    BULLETIN_ID = "BULLETIN_ID"


class DefaultAlliancePosition(str, Enum):
    REMOVE = "REMOVE"
    APPLICANT = "APPLICANT"
    MEMBER = "MEMBER"
    OFFICER = "OFFICER"
    HEIR = "HEIR"
    LEADER = "LEADER"


class OrderByRelationAggregateFunction(str, Enum):
    COUNT = "COUNT"


class OrderByRelationWithColumnAggregateFunction(str, Enum):
    AVG = "AVG"
    MIN = "MIN"
    MAX = "MAX"
    SUM = "SUM"
    COUNT = "COUNT"
