# Generated by ariadne-codegen
# Source: resources/queries.graphql

from typing import List, Optional

from .base_model import BaseModel
from .fragments import SubscriptionAllianceFields


class GetSubscriptionAlliance(BaseModel):
    alliances: Optional["GetSubscriptionAllianceAlliances"]


class GetSubscriptionAllianceAlliances(BaseModel):
    data: List["GetSubscriptionAllianceAlliancesData"]


class GetSubscriptionAllianceAlliancesData(SubscriptionAllianceFields):
    pass


GetSubscriptionAlliance.model_rebuild()
GetSubscriptionAllianceAlliances.model_rebuild()
