# Generated by ariadne-codegen
# Source: resources/queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import CityFields, PaginatorFields


class GetCities(BaseModel):
    cities: "GetCitiesCities"


class GetCitiesCities(BaseModel):
    data: List["GetCitiesCitiesData"]
    paginator_info: "GetCitiesCitiesPaginatorInfo" = Field(alias="paginatorInfo")


class GetCitiesCitiesData(CityFields):
    pass


class GetCitiesCitiesPaginatorInfo(PaginatorFields):
    pass


GetCities.model_rebuild()
GetCitiesCities.model_rebuild()
